apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-go-web-server
  name: simple-go-web-server
  namespace: demo
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-go-web-server
  type: ClusterIP
